##### 1. Introdução ao Pandas

In [3]:
!pip install -q -U watermark

In [2]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy

In [5]:
%watermark --iversions

matplotlib: 3.10.0
numpy     : 2.1.3
pandas    : 2.2.3

##### Estruturas de Dados - Series e DataFrames

- Uma série é uma estrutura de uma dimensão
- Um DataFrame é similar a uma tabela

In [7]:
# Criação da Serie
s = pd.Series([10, 20, 30, 40, 50], name = "Valores")

print(type(s))
print()
print(s)

<class 'pandas.core.series.Series'>

0    10
1    20
2    30
3    40
4    50
Name: Valores, dtype: int64

In [15]:
# Criação de um DataFrame

# 1. Cria-se um dicionário

dados = {
    "Nome": ["Ana", "Bruno", "Fabiana", "Ronaldo", "Eliana", "Matias"],
    "Idade": [28, 34, 29, 17, None, 78],
    "Cidade": ["Blumenau", "São Paulo", "Blumenau", "São Paulo", "Salvador", "São Paulo"],
    "Salário": [None, 7500, 6200, 9300, 8100, 15400]
}

# Convertendo para DataFrame

df = pd.DataFrame(dados)
df.head()

      Nome  Idade     Cidade  Salário
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6200.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0

##### 2. Leitura e Escrita de Dados no formato CSV

In [16]:
# Salvando (Escrevendo) o DataFrame em um arquivo CSV

# index = False evita que o índice do DataFrame seja salvo como uma coluna no CSV
df.to_csv("Dados.csv", index=False, encoding="utf-8")

In [17]:
# Incluindo o índice
df.to_csv("Dados_Com_Indice.csv", index=True, encoding="utf-8")

In [19]:
# Lendo Arquivos CSV
df_read_csv = pd.read_csv("Dados_Com_Indice.csv")
df_read_csv.head()

   Unnamed: 0     Nome  Idade     Cidade  Salário
0           0      Ana   28.0   Blumenau      NaN
1           1    Bruno   34.0  São Paulo   7500.0
2           2  Fabiana   29.0   Blumenau   6200.0
3           3  Ronaldo   17.0  São Paulo   9300.0
4           4   Eliana    NaN   Salvador   8100.0

In [22]:
# Deletando a coluna de índice 0

df_read_csv.drop(df_read_csv.columns[0], axis=1)

      Nome  Idade     Cidade  Salário
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6200.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0
5   Matias   78.0  São Paulo  15400.0

##### 3. Seleção e Indexação com Pandas

In [24]:
# Visualizando as primeiras linhas
df.head()

      Nome  Idade     Cidade  Salário
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6200.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0

In [27]:
# Selecionando uma unica coluna do DataFrame

name = df["Nome"]
name.head()

0        Ana
1      Bruno
2    Fabiana
3    Ronaldo
4     Eliana
Name: Nome, dtype: object

In [28]:
# Selecionando mais de uma coluna

info_pessoal = df[["Nome", "Cidade"]]
info_pessoal.head()

      Nome     Cidade
0      Ana   Blumenau
1    Bruno  São Paulo
2  Fabiana   Blumenau
3  Ronaldo  São Paulo
4   Eliana   Salvador

##### loc e iloc

O loc é usado com a combinação de um índice (referente à linha) e uma coluna ou conjunto de colunas

In [32]:
nome = df.loc[1, ["Nome", "Cidade"]]
nome.head()

Nome          Bruno
Cidade    São Paulo
Name: 1, dtype: object

O iloc usa um par com o índice da linha e um índice da coluna, ele não contabiliza a coluna de índices

In [35]:
dados_fabi = df.iloc[2, [0, 1, 2, 3]]
print(df)
print()
print(dados_fabi)

      Nome  Idade     Cidade  Salário
0      Ana   28.0   Blumenau      NaN
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6200.0
3  Ronaldo   17.0  São Paulo   9300.0
4   Eliana    NaN   Salvador   8100.0
5   Matias   78.0  São Paulo  15400.0

Nome        Fabiana
Idade          29.0
Cidade     Blumenau
Salário      6200.0
Name: 2, dtype: object

In [38]:
# Selecionando um intervalo de linhas e todas as colunas

# Os fatiamentos para iloc e loc são diferentes, o loc é inclusivo, o iloc é exclusivo

all_columns_1_3_lines = df.iloc[1:3]
all_columns_1_3_lines.head()

      Nome  Idade     Cidade  Salário
1    Bruno   34.0  São Paulo   7500.0
2  Fabiana   29.0   Blumenau   6200.0